server:
  port: 9000

spring:
  http.converters.preferred-json-mapper: jackson
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:book-server;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        hbm2ddl:
          auto: create-drop

# configurações para acesso ao OAuth2 Provider
bookserver:
  authorization-server: http://localhost:8080
  client-details:
    client-id: cliente-curl
    client-secret: 123456
    redirect-uri: http://localhost:9000/bookserver/callback
